# Generated by Django 5.1.6 on 2025-02-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.IntegerField()),
                ('assured_age', models.IntegerField()),
                ('nominee_relation', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('policy_sum_assured', models.IntegerField()),
                ('premium', models.FloatField()),
                ('premium_payment_mode', models.CharField(max_length=50)),
                ('annual_income', models.IntegerField()),
                ('holder_marital_status', models.CharField(max_length=50)),
                ('indiv_requirement_flag', models.CharField(max_length=10)),
                ('policy_term', models.IntegerField()),
                ('policy_payment_term', models.IntegerField()),
                ('product_type', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('bank_code', models.FloatField(blank=True, null=True)),
                ('policy_risk_commencement_date', models.DateTimeField()),
                ('date_of_death', models.DateTimeField()),
                ('intimation_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('sub_status', models.CharField(max_length=100)),
            ],
        ),
    ]
